### ISSUE TITLE
Does propeller supported in android armv8-a?

### ISSUE THREAD

**Issue by zhang-hply** [google/llvm-propeller#273] opened 2024-12-25 09:41 UTC
I try to follow this [Enabling AutoFDO & Propeller optimizations on Arm with SPE](https://discourse.llvm.org/t/enabling-autofdo-propeller-optimizations-on-arm-with-spe/78980) to make propeller valid in android armv8-a. But I'm stuck in executing this command due to no __arm_spe__ event for simpleperf.
```
perf record --no-switch-events \
  -e 'arm_spe_0/branch_filter=1,load_filter=0,store_filter=0,jitter=1/' \
  -c 10007 -N -o /tmp/spe.perf.data -- \
    $BINDIR/proto_benchmark_base --benchmark_min_time=30s \
    --hugepage_text=true --benchmark_filter=all
```
Do you have and idea about it?

Thx

**Comment by dhoekwater** [comment] 2024-12-26 07:06
Your options largely depend on what PMU events you *do* have available. If SPE isn't an option, I'd recommend trying ETM since ETM data can be converted to Perf branch stack data (just like Intel LBR / AMD IBS); see [this article](android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/collect_etm_data_for_autofdo.md) for how to generate LBR-like data from ETM data.

For now, marking this as a duplicate of #86 since the use case and answer are both largely the same.

**Closed by dhoekwater** 2024-12-26 07:06 UTC
